FROM registry.access.redhat.com/ubi10/openjdk-21 AS build

USER 0

WORKDIR /build

COPY pom.xml settings.xml ./
COPY src/ src/

RUN mvn package -s settings.xml -DskipTests

FROM registry.access.redhat.com/ubi10/openjdk-21-runtime

COPY --from=build /build/target/*-runner.jar /deployments/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/deployments/app.jar"]
