---
# Deploy a new application version on the current host.
# Required variable: app_release_version

- name: Deploy application release ({{ app_release_deployment_mode }} mode)
  ansible.builtin.include_tasks: "deploy_{{ app_release_deployment_mode }}.yml"
...
